- project:
    name: openstack/os-client-config
    templates:
      - shade-tox-tips
    check:
      jobs:
        - osc-functional-devstack-tips
    gate:
      jobs:
        - osc-functional-devstack-tips
