- project:
    name: openstack/os-client-config
    templates:
      - shade-functional-tips
      - shade-tox-tips
    check:
      jobs:
        - legacy-osc-dsvm-functional-tips:
            voting: false
